netizenorg/netnet.studio

- www/css/styles.css
- www/js/TextBubble.js
just opening this change as a pr because i messed in TextBubble.js a little
(inside updatePosition() to adjust arrow positioning)
> thin out border

- www/css/search-bar.css
- www/css/styles.css
- www/js/SearchBar.js
styles & some transitions & click-bg-to-close functionality
> search bar

- www/css/hvp-ui.css
one last PR on this branch
addressed the video progress bar in firefox issue ⛱️
> redo firefox styling

- www/js/Widget.js
modified the on() to create empty event arrays in the events object for new event types.
Also added the emit function which aims to loop through and fire the functions stored in the the callback array
> 70 update widget events

- www/css/widget-styles.css
- www/js/Widget.js
a marquee-scroll solution for truncated titles on misc widgets (mostly seen in tutorials). any feedback on how this is working/looking on your machines/screens/browsers would be super helpful! @nbriz @il41
> marquee title animation

- www/convos/browser-fest/index.js
- www/convos/functions-menu/index.js
- www/convos/student-session/index.js
- www/convos/tutorials-guide/index.js
- www/convos/utils-misc/index.js
- www/js/utils.js
- www/widgets/BrowserFest.js
- www/widgets/FunctionsMenu.js
- www/widgets/StudentSession.js
- www/widgets/TutorialsGuide.js
better gh-auth redirection logic/dialogue
> BrowserFest Updates

- data/examples-urls.json
- www/data/learning-guide-tuts.html
- www/tutorials/list.json
- www/widgets/HyperVideoPlayer.js
- www/widgets/TutorialMaker.js
- www/widgets/TutorialsGuide.js
bug fixes, updates && new CSS tutorial
> new tutorial for BF + bug fixes

- my_modules/github.js
- www/convos/functions-menu/index.js
- www/convos/project-files/index.js
- www/convos/student-session/index.js
- www/convos/utils-misc/index.js
- www/js/NetNet.js
- www/js/utils.js
- www/widgets/CSSReference.js
- www/widgets/FunctionsMenu.js
- www/widgets/HTMLReference.js
- www/widgets/JSReference.js
- www/widgets/ProjectFiles.js
- www/widgets/StudentSession.js
after the stresstest that was BrowserFest, there were a series of bugs/issues that came up, most notably the fact that while referencing local assets in a gh project like this would work:
```html
```
referencing local files like this would not:
```html
<link rel="stylesheet" href="css/styles.css">
<script src="main.js"></script>
```
this && other related fixes/improvements are in this PR
> Post BrowserFest edits + Bug Fixes

- my_modules/github.js
> fixing gh proxy bug caused byredbird proxy

- www/data/references/html-reference.json
- www/js/NetNet.js
- www/widgets/HTMLReference.js
- www/widgets/KeyboardShortcuts.js
- www/widgets/ProjectFiles.js
general updates + bugs while working on HTML tutorials
> General Updates: HTML tutorials

- data/examples-map.json
- data/examples/60--xmlhttprequest.json
- data/examples/61--fetch_api.json
- data/examples/62--async___await.json
- www/js/utils.js
> new REST API exampes

- www/widgets/FunctionsMenu.js
- www/widgets/KeyboardShortcuts.js
when the student manually runs the render update `WIDGETS['functions-menu'].runUpdate()` it also clears the Web Console (to remove any prior error messages)
> clearing on update

- www/convos/code-examples/index.js
Changed a little bit of netnet dialogue in the www>convos>code-example directory to test a pull request.
> Edited a bit of netnet's dialogue for a PR test 

- .gitignore
- .gitmodules
- my_modules/routes.js
- my_modules/setup-script.js
- package.json
- www/convos/code-review/index.js
- www/convos/example-convo/index.js
- www/convos/functions-menu/index.js
- www/convos/student-session/index.js
- www/data/references/html-reference.json
- www/index.html
- www/js/NetNet.js
- www/js/custom-elements/code-slider.js
- www/js/utils.js
- www/widgets/BrowserFest.js
- www/widgets/CSSReference.js
- www/widgets/CodeReview.js
- www/widgets/ColorWidget.js
- www/widgets/CssGradientWidget.js
- www/widgets/FunctionsMenu.js
- www/widgets/ProjectFiles.js
- www/widgets/StudentSession.js
rather than being dependent on  [Maths.js](https://github.com/nbriz/Maths), [Color.js](https://github.com/nbriz/Color), [Averigua.js](https://github.com/nbriz/Averigua) and [FileUploader.js](https://github.com/nbriz/FileUploader) individually as `node_modules`, these have now been grouped into a single lib (which can also be used by students on netnet itself) called [netnet-standard-library](https://github.com/netizenorg/netnet-standard-library) 
this lib, as well as the netitor, are now being included as git [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) which should be less buggy when pulling updates.
> Git submodules

- www/widgets/CSSReference.js
- www/widgets/ColorWidget.js
changed all `nn.match` (which doesn't exist) to `nn.colorMatch`
> fixed nn.match bug

- www/data/references/js-reference-main.html
- www/js/custom-elements/svg-js-variable.js
Added a new diagram to JS Reference for a variable diagram. This is the first of a few more incoming, but starting the PR now to start discussion. You can preview the additions in the dev server here:
[http://localhost:8001/?w=js-reference](http://localhost:8001/?w=js-reference)
> Added JavaScript variable diagram

- .gitignore
attempting to resolve divergent branches...
> ignoring gh tmp user data files

- www/core/utils.js
Received an error in the console: `ReferenceError: ob is not defined`. Typo fixed on line 596.
> Error Fixed: ReferenceError: ob is not defined

- www/assets/images/widgets/draggable-dots.svg
- www/assets/images/widgets/info-button.svg
- www/core/styles/base.css
- www/core/utils.js
- www/custom-elements/misc/reorderable-list/index.js
- www/custom-elements/misc/reorderable-list/styles.css
- www/widgets/demo-example-maker/index.js
- www/widgets/demo-example-maker/styles.css
**Finished the working version of the custom reorderable list!** 🎉
Reorderable list additions:
- Custom reorderable list created w/ styles
- Updated DEM to functionally work w/ new element
- Added a function to add IDs to future uploaded sketches w/out
Additional changes made:
- Removed `appearence: none;' under www/core/styles/base.css
[ This was causing the checkbox input element to not display ]
- Changed the DEM text input styles to fit the widget better
I am sure my code is not the most simplified, so let me know if there is anything I should change. I did run it through a JS standard checker and it looked good to go. (There were some flags on the DEM index.js, but not on things I added, so I left them alone) Additionally, I tried to troubleshoot this element to make sure everything …
> Issue #236: DemoExampleMaker: re-order steps functionality

- www/widgets/styles.css
widget top buttons
from this:
to this:
> small expand / close button update

- docs/developers/contributor-workflow.md
- docs/developers/manual-setup.md
- package.json
- www/core/utils.js
- www/widgets/code-review/index.js
- www/widgets/css-reference/data/edu-supplement.json
- www/widgets/css-reference/index.js
- www/widgets/html-reference/data/edu-supplement.json
- www/widgets/html-reference/index.js
- www/widgets/js-reference/index.js
created a single npm script for pulling updates to sub-modules `npm run pull-modules` && integrated loads of updates from the netitor sub-module && the netnet-standard-library module. made updates/changes to netnet edu supplement data && logic to work with these updates.
netitor updates (git log):
- better edu-info for style attribute and element
- now parsing style attribute values with edu data
- added nn snippets
- updated b,u,i element info
- updated nn.min.js edu info and docs
- improved object property/method edu-info
- added gsap snippet
- added creative coding lib CDN && template hinting
- better logic for spotting missing tag bracket errors
- improved missing tag pair friendly error logic
- improved CSS edu info
- edu info improvements
- only hinting svg elments within svg tags
- …
> loads of updates to sub-modules && related logic
